---
# demo-spring application properties file
server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2KB

# Management and Actuator Configuration
management:
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: "demo-spring"
        version: "1.0.0"
# Add field source to identify logs from different environments




  level:
    root: "INFO"
    #    org.springframework.web: INFO
    com.eguisse.demospring: ${LOG_LEVEL:INFO}
#    org.springframework.security.web: DEBUG
#    redis.clients.jedis: ${LOG_LEVEL:DEBUG}


# Spring Configuration
spring:
  application:
    name: demo-spring

# Enable Swagger UI and API docs
springdoc:
  api-docs:
    integration:



  swagger-ui:
    enabled: true